name: ssl-wearables
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - scikit-learn>=1.3
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - seaborn>=0.12
  - jupyter
  - ipykernel
  - scipy>=1.10
  - pip
  - pip:
    - accelerometer-features
    - neurokit2
    - imbalanced-learn
    - optuna
    - shap
    - tqdm
    - tensorboard
    - git+https://github.com/OxWearables/ssl-wearables.git